spring.application.name: api-gateway
server.port: ${PORT:8080}
eureka.client.serviceUrl.defaultZone: http://localhost:${EUREKA_PORT:8010}/eureka

spring.main.web-application-type: reactive

#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

spring:
  cloud:
    gateway:
      routes[0]:
        id: order-ws-permit-all-endpoints
        uri: lb://order-ws
        predicates[0]: Path=/order-ws/rest/api/orders/**
        predicates[1]: Method=GET,PUT,DELETE,POST
        predicates[2]: After=2024-06-18T15:00:00.000+02:00[Europe/Prague]
        filters[0]: RewritePath=/order-ws/(?<segment>.*), /$\{segment}
#        filters[0]: RewritePath=/user-ws/rest/api/orders/status/check,/rest/api/orders/status/check
      routes[1]:
        id: user-ws-permit-all-endpoints
        uri: lb://user-ws
        predicates[0]: Path=/user-ws/rest/api/users/**
        predicates[1]: Method=GET,PUT,DELETE,POST
        filters[0]: RewritePath=/user-ws/(?<segment>.*), /$\{segment}
      routes[2]:
        id: inventory-ws-permit-all-endpoints
        uri: lb://inventory-ws
        predicates[0]: Path=/inventory-ws/rest/api/inventory/**
        predicates[1]: Method=GET,PUT,DELETE,POST
        filters[0]: RewritePath=/inventory-ws/(?<segment>.*), /$\{segment}
